# Atuin - shell history

## Search UX
style = "full"
inline_height = 30
show_preview = true
show_help = true
show_tabs = false
time_format = ""

## Search behavior
search_mode = "fuzzy"

## Privacy
history_filter = [
  "^export.*TOKEN",
  "^export.*SECRET",
  "^export.*KEY",
  "^export.*PASSWORD",
]

## Quality of life
update_check = false
enter_accept = true
keymap_mode = "vim-normal"

## Disable sync
sync_frequency = "0"
