-- Autocmds are loaded on VeryLazy. LazyVim's defaults (highlight on yank, resize
-- splits, restore cursor, close-with-q, auto-mkdir on save, spell/wrap for text
-- filetypes, checktime on focus) live in lazyvim/config/autocmds.lua.
-- The chezmoi apply-on-save watcher comes from the util.chezmoi extra.
